# Generated by Django 4.2.5 on 2024-05-31 14:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shiftmeal',
            name='shift',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='api.shift'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='shiftmanager',
            name='shift',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.shift'),
        ),
        migrations.AlterField(
            model_name='shiftmanager',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
