# Generated by Django 4.2.5 on 2024-05-31 15:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_shiftmeal_shift_alter_shiftmanager_shift_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='meal',
            options={'verbose_name': 'وعده', 'verbose_name_plural': 'وعده ها'},
        ),
        migrations.AlterModelOptions(
            name='shift',
            options={'verbose_name': 'شیفت', 'verbose_name_plural': 'شیفت ها'},
        ),
        migrations.AlterModelOptions(
            name='shiftmanager',
            options={'verbose_name': 'مدیر شیفت', 'verbose_name_plural': 'مدیران شیفت'},
        ),
        migrations.AlterModelOptions(
            name='shiftmeal',
            options={'verbose_name': 'وعده شیفت', 'verbose_name_plural': 'وعده های شیفت'},
        ),
        migrations.AlterModelOptions(
            name='supervisorrecord',
            options={'verbose_name': 'مسیولیت', 'verbose_name_plural': 'مسیولیت ها'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'کاربر', 'verbose_name_plural': 'کاربران'},
        ),
        migrations.AlterModelOptions(
            name='workflow',
            options={'verbose_name': 'ساعت کاری', 'verbose_name_plural': 'ساعت کاری ها'},
        ),
        migrations.AlterField(
            model_name='meal',
            name='daily_meal',
            field=models.CharField(choices=[('breakfast', 'صبحانه')], max_length=50, verbose_name='وعده غذا'),
        ),
        migrations.AlterField(
            model_name='meal',
            name='food',
            field=models.CharField(choices=[('pizza', 'pizza')], max_length=50, verbose_name='نام غذا'),
        ),
        migrations.AlterField(
            model_name='meal',
            name='food_type',
            field=models.CharField(choices=[('type1', 'type1')], max_length=50, verbose_name='نوع غذا'),
        ),
        migrations.AlterField(
            model_name='shift',
            name='shift_name',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=100, verbose_name='نوع شیفت'),
        ),
        migrations.AlterField(
            model_name='shiftmanager',
            name='shift',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.shift', verbose_name='شیفت'),
        ),
        migrations.AlterField(
            model_name='shiftmanager',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر'),
        ),
        migrations.AlterField(
            model_name='shiftmeal',
            name='meal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.meal', verbose_name='وعده'),
        ),
        migrations.AlterField(
            model_name='shiftmeal',
            name='shift',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.shift', verbose_name='شیفت'),
        ),
        migrations.AlterField(
            model_name='supervisorrecord',
            name='supervisor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.shiftmanager', verbose_name='منصوب کننده'),
        ),
        migrations.AlterField(
            model_name='supervisorrecord',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر'),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile',
            field=models.ImageField(blank=True, default='defaults/user.png', null=True, upload_to='profiles/', verbose_name='پروفایل'),
        ),
    ]
