# Generated by Django 4.2.5 on 2024-07-22 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_user_reset_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drink',
            name='meal',
        ),
        migrations.AddField(
            model_name='meal',
            name='drinks',
            field=models.ManyToManyField(to='api.drink'),
        ),
    ]
