# Generated by Django 4.2.5 on 2024-06-04 15:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_user_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meal',
            name='food1',
        ),
        migrations.RemoveField(
            model_name='meal',
            name='food2',
        ),
        migrations.AddField(
            model_name='meal',
            name='food',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='meals', to='api.food', verbose_name='غذا'),
            preserve_default=False,
        ),
    ]
