# Generated by Django 4.2.5 on 2024-07-23 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_drink_meal_meal_drinks'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='working_shift',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], default='B', max_length=100, verbose_name='شیفت کاری'),
        ),
        migrations.AlterField(
            model_name='meal',
            name='drinks',
            field=models.ManyToManyField(to='api.drink', verbose_name='نوشیدنی ها'),
        ),
    ]
