# Generated by Django 4.2.5 on 2024-05-31 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_meal_food_alter_shiftmeal_shift'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='food',
            field=models.CharField(max_length=500, verbose_name='2نام غذا'),
        ),
    ]
