# Generated by Django 4.2.5 on 2024-05-31 20:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_meal_food'),
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام غذا')),
            ],
        ),
        migrations.AlterField(
            model_name='meal',
            name='food',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.food'),
        ),
    ]
