# Generated by Django 4.2.5 on 2024-05-31 20:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_food_alter_meal_food'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='food',
            options={'verbose_name': 'غذا', 'verbose_name_plural': 'غذا ها'},
        ),
        migrations.RemoveField(
            model_name='meal',
            name='food',
        ),
        migrations.AddField(
            model_name='meal',
            name='food1',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='first_meals', to='api.food', verbose_name='غذای 1'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='meal',
            name='food2',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='second_meals', to='api.food', verbose_name='غذای 2'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='meal',
            name='daily_meal',
            field=models.CharField(choices=[('lunch', 'ناهار'), ('dinner', 'شام'), ('diet', 'غذای رژیمی')], max_length=50, verbose_name='وعده غذا'),
        ),
    ]
