# Generated by Django 4.2.5 on 2024-07-23 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_rename_supervisor_supervisorrecord_shift_manager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='drinks',
            field=models.ManyToManyField(blank=True, to='api.drink', verbose_name='نوشیدنی ها'),
        ),
    ]
